export default () => ({
  PORT: process.env.PORT,
  ORIGIN: process.env.ORIGIN,
  POSTGRESQL_HOST: process.env.POSTGRESQL_HOST,
  POSTGRESQL_PORT: process.env.POSTGRESQL_PORT,
  POSTGRESQL_USERNAME: process.env.POSTGRESQL_USERNAME,
  POSTGRESQL_PASSWORD: process.env.POSTGRESQL_PASSWORD,
  POSTGRESQL_DATABASE: process.env.POSTGRESQL_DATABASE,
  JWT_SECRET: process.env.JWT_SECRET,
  STEAM_API_KEY: process.env.STEAM_API_KEY,
  STEAM_API_URL: process.env.STEAM_API_URL,
});
